// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/eclipse-iofog/iofog-operator/pkg/apis/iokog/v1alpha1.Kog":       schema_pkg_apis_iokog_v1alpha1_Kog(ref),
		"github.com/eclipse-iofog/iofog-operator/pkg/apis/iokog/v1alpha1.KogSpec":   schema_pkg_apis_iokog_v1alpha1_KogSpec(ref),
		"github.com/eclipse-iofog/iofog-operator/pkg/apis/iokog/v1alpha1.KogStatus": schema_pkg_apis_iokog_v1alpha1_KogStatus(ref),
	}
}

func schema_pkg_apis_iokog_v1alpha1_Kog(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Kog is the Schema for the kogs API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/eclipse-iofog/iofog-operator/pkg/apis/iokog/v1alpha1.KogSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/eclipse-iofog/iofog-operator/pkg/apis/iokog/v1alpha1.KogStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/eclipse-iofog/iofog-operator/pkg/apis/iokog/v1alpha1.KogSpec", "github.com/eclipse-iofog/iofog-operator/pkg/apis/iokog/v1alpha1.KogStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_iokog_v1alpha1_KogSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KogSpec defines the desired state of Kog",
				Properties: map[string]spec.Schema{
					"controllerCount": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"connectorCount": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"controllerImage": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"connectorImage": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"operatorImage": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"kubeletImage": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"database": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/eclipse-iofog/iofog-operator/pkg/apis/iokog/v1alpha1.Database"),
						},
					},
				},
				Required: []string{"controllerCount", "connectorCount", "controllerImage", "connectorImage", "operatorImage", "kubeletImage", "database"},
			},
		},
		Dependencies: []string{
			"github.com/eclipse-iofog/iofog-operator/pkg/apis/iokog/v1alpha1.Database"},
	}
}

func schema_pkg_apis_iokog_v1alpha1_KogStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KogStatus defines the observed state of Kog",
				Properties: map[string]spec.Schema{
					"controllerPods": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"connectorPods": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"controllerCount": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"connectorCount": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
				},
				Required: []string{"controllerPods", "connectorPods", "controllerCount", "connectorCount"},
			},
		},
		Dependencies: []string{},
	}
}
