apiVersion: apps/v1
kind: Deployment
metadata:
  name: iofog-operator
  namespace: default
  labels:
    name: iofog-operator
spec:
  selector:
    matchLabels:
      name: iofog-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: iofog-operator
    spec:
      containers:
      - command:
        - iofog-operator
        args:
        - --enable-leader-election
        image: gcr.io/focal-freedom-236620/operator:develop
        name: iofog-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: iofog-operator
      terminationGracePeriodSeconds: 10
