apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iofog-operator
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - iofog.org
  resources:
  - apps
  - controlplanes
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - configmaps/status
  - events
  - serviceaccounts
  - services
  - persistentvolumeclaims
  - secrets
  verbs:
  - '*'