
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.iofog.org
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.iofog.org
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - controlplanes.iofog.org
  resources:
  - controlplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplanes.iofog.org
  resources:
  - controlplanes/status
  verbs:
  - get
  - patch
  - update
