---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datasance.com
  resources:
  - applications
  - controlplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datasance.com
  resources:
  - applications/finalizers
  - applications/status
  - controlplanes/finalizers
  - controlplanes/status
  verbs:
  - get
  - patch
  - update
