/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"time"

	v1alpha2 "github.com/eclipse-iofog/iofog-operator/pkg/apis/k8s/v1alpha2"
	scheme "github.com/eclipse-iofog/iofog-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KogsGetter has a method to return a KogInterface.
// A group's client should implement this interface.
type KogsGetter interface {
	Kogs(namespace string) KogInterface
}

// KogInterface has methods to work with Kog resources.
type KogInterface interface {
	Create(*v1alpha2.Kog) (*v1alpha2.Kog, error)
	Update(*v1alpha2.Kog) (*v1alpha2.Kog, error)
	UpdateStatus(*v1alpha2.Kog) (*v1alpha2.Kog, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.Kog, error)
	List(opts v1.ListOptions) (*v1alpha2.KogList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.Kog, err error)
	KogExpansion
}

// kogs implements KogInterface
type kogs struct {
	client rest.Interface
	ns     string
}

// newKogs returns a Kogs
func newKogs(c *K8sV1alpha2Client, namespace string) *kogs {
	return &kogs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kog, and returns the corresponding kog object, and an error if there is any.
func (c *kogs) Get(name string, options v1.GetOptions) (result *v1alpha2.Kog, err error) {
	result = &v1alpha2.Kog{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kogs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Kogs that match those selectors.
func (c *kogs) List(opts v1.ListOptions) (result *v1alpha2.KogList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.KogList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kogs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kogs.
func (c *kogs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kogs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a kog and creates it.  Returns the server's representation of the kog, and an error, if there is any.
func (c *kogs) Create(kog *v1alpha2.Kog) (result *v1alpha2.Kog, err error) {
	result = &v1alpha2.Kog{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kogs").
		Body(kog).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kog and updates it. Returns the server's representation of the kog, and an error, if there is any.
func (c *kogs) Update(kog *v1alpha2.Kog) (result *v1alpha2.Kog, err error) {
	result = &v1alpha2.Kog{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kogs").
		Name(kog.Name).
		Body(kog).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *kogs) UpdateStatus(kog *v1alpha2.Kog) (result *v1alpha2.Kog, err error) {
	result = &v1alpha2.Kog{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kogs").
		Name(kog.Name).
		SubResource("status").
		Body(kog).
		Do().
		Into(result)
	return
}

// Delete takes name of the kog and deletes it. Returns an error if one occurs.
func (c *kogs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kogs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kogs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kogs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kog.
func (c *kogs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.Kog, err error) {
	result = &v1alpha2.Kog{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kogs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
