apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "datasance.com/v3",
          "kind": "ControlPlane",
          "metadata": {
            "name": "pot"
          },
          "spec": {
            "replicas": {
              "controller": 2,
              "nats": 2
            },
            "database": {
              "provider": "postgres",
              "user": null,
              "host": null,
              "port": null,
              "password": null,
              "databaseName": null
            },
            "auth": {
              "mode": "embedded",
              "bootstrap": {
                "username": "admin",
                "password": null
              }
            },
            "images": {
              "pullSecret": null,
              "controller": null,
              "router": null,
              "nats": null
            },
            "services": {
              "controller": {
                "type": null,
                "annotations": null
              },
              "router": {
                "type": null,
                "annotations": null
              },
              "nats": {
                "type": "ClusterIP",
                "annotations": null
              },
              "natsServer": {
                "type": "ClusterIP",
                "annotations": null
              }
            },
            "controller": {
              "publicUrl": null,
              "trustProxy": false,
              "consoleUrl": null,
              "consolePort": 0,
              "pidBaseDir": "",
              "https": false,
              "secretName": null,
              "logLevel": "info"
            },
            "ingresses": {
              "controller": {
                "annotations": null,
                "ingressClassName": null,
                "host": null,
                "secretName": null
              },
              "router": {
                "address": null,
                "messagePort": 5671,
                "interiorPort": 55671,
                "edgePort": 45671
              },
              "nats": {
                "address": null,
                "serverPort": 4222,
                "clusterPort": 6222,
                "leafPort": 7422,
                "mqttPort": 8883,
                "httpPort": 8222
              }
            }
          },
          "status": {
            "conditions": [
              {
                "lastTransitionTime": "2022-04-10T22:44:09Z",
                "message": "",
                "reason": "initial_status",
                "status": "True",
                "type": "deploying"
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
  name: iofog-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ControlPlane deploys and manages the ioFog control plane.
      kind: ControlPlane
      name: controlplanes.datasance.com
      version: v3
  description: ioFog Control Plane on Kubernetes
  displayName: iofog-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - iofog
  - datasance
  - pot
  links:
  - name: Datasance PoT // Iofog Operator
    url: https://datasance.com
  maturity: stable
  minKubeVersion: 1.18.0
  provider:
    name: Datasance
  version: 0.0.0
