/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	time "time"

	k8sv1alpha2 "github.com/eclipse-iofog/iofog-operator/pkg/apis/k8s/v1alpha2"
	versioned "github.com/eclipse-iofog/iofog-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/eclipse-iofog/iofog-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/eclipse-iofog/iofog-operator/pkg/client/listers/k8s/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KogInformer provides access to a shared informer and lister for
// Kogs.
type KogInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.KogLister
}

type kogInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKogInformer constructs a new informer for Kog type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKogInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKogInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKogInformer constructs a new informer for Kog type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKogInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1alpha2().Kogs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1alpha2().Kogs(namespace).Watch(options)
			},
		},
		&k8sv1alpha2.Kog{},
		resyncPeriod,
		indexers,
	)
}

func (f *kogInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKogInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kogInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&k8sv1alpha2.Kog{}, f.defaultInformer)
}

func (f *kogInformer) Lister() v1alpha2.KogLister {
	return v1alpha2.NewKogLister(f.Informer().GetIndexer())
}
