/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/eclipse-iofog/iofog-operator/pkg/apis/k8s/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKogs implements KogInterface
type FakeKogs struct {
	Fake *FakeK8sV1alpha2
	ns   string
}

var kogsResource = schema.GroupVersionResource{Group: "k8s.iofog.org", Version: "v1alpha2", Resource: "kogs"}

var kogsKind = schema.GroupVersionKind{Group: "k8s.iofog.org", Version: "v1alpha2", Kind: "Kog"}

// Get takes name of the kog, and returns the corresponding kog object, and an error if there is any.
func (c *FakeKogs) Get(name string, options v1.GetOptions) (result *v1alpha2.Kog, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kogsResource, c.ns, name), &v1alpha2.Kog{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Kog), err
}

// List takes label and field selectors, and returns the list of Kogs that match those selectors.
func (c *FakeKogs) List(opts v1.ListOptions) (result *v1alpha2.KogList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kogsResource, kogsKind, c.ns, opts), &v1alpha2.KogList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.KogList{ListMeta: obj.(*v1alpha2.KogList).ListMeta}
	for _, item := range obj.(*v1alpha2.KogList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kogs.
func (c *FakeKogs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kogsResource, c.ns, opts))

}

// Create takes the representation of a kog and creates it.  Returns the server's representation of the kog, and an error, if there is any.
func (c *FakeKogs) Create(kog *v1alpha2.Kog) (result *v1alpha2.Kog, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kogsResource, c.ns, kog), &v1alpha2.Kog{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Kog), err
}

// Update takes the representation of a kog and updates it. Returns the server's representation of the kog, and an error, if there is any.
func (c *FakeKogs) Update(kog *v1alpha2.Kog) (result *v1alpha2.Kog, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kogsResource, c.ns, kog), &v1alpha2.Kog{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Kog), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKogs) UpdateStatus(kog *v1alpha2.Kog) (*v1alpha2.Kog, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kogsResource, "status", c.ns, kog), &v1alpha2.Kog{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Kog), err
}

// Delete takes name of the kog and deletes it. Returns an error if one occurs.
func (c *FakeKogs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kogsResource, c.ns, name), &v1alpha2.Kog{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKogs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kogsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.KogList{})
	return err
}

// Patch applies the patch and returns the patched kog.
func (c *FakeKogs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.Kog, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kogsResource, c.ns, name, pt, data, subresources...), &v1alpha2.Kog{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Kog), err
}
